export const Reg=[
    {
        score:'15632',
        course:'Mathematics'
    },
    {
        score:'15632',
        course:'Medicine'
    },
    {
        score:'14632',
        course:'Banking and Finance'
    },
    {
        score:'15612',
        course:'Accounting'
    },
    {
        score:'12232',
        course:'Human Anatomy'
    },
    {
        score:'14632',
        course:'Mechanical'
    },
    {
        score:'15532',
        course:'Computer'
    },
    {
        score:'15611',
        course:'Programming'
    },
    {
        score:'13232',
        course:'Mathematics'
    },
    {
        score:'11132',
        course:'Accounting'
    },
    {
        score:'13432',
        course:'English'
    },
    {
        score:'15632',
        course:'Mathematics'
    },
    {
        score:'11232',
        course:'Medicine'
    },
]